---
# tasks file for roles/sgws_config

#=== Grid's section ===#
- import_tasks: sgws_authorize.yml

#--- SSL Certificates ---#
#- import_tasks: sgws_api_mgmt_cert_{{ api_mgmt_cert_state }}.yml
#- import_tasks: sgws_api_stor_cert_{{ api_stor_cert_state }}.yml

#--- Indentity provider ---#
#- import_tasks: sgws_identity.yml

#--- Groups and users ---#
- import_tasks: sgws_groups.yml

#--- Tenant's account ---#
- import_tasks: sgws_accounts.yml

#=== Tenant's section ===#
- import_tasks: sgws_org_authorize.yml

#--- Indentity provider ---#
#- import_tasks: sgws_org_identity.yml

#--- Groups and users ---#
- import_tasks: sgws_org_groups.yml

#--- S3 keys ---#
- import_tasks: sgws_org_s3keys.yml

#--- Bucket ---#
- import_tasks: sgws_org_bucket.yml
