---
- name: Install signed SSL certificate for management API
  uri:
    url: https://{{grid_admn}}/api/v2/grid/management-certificate/update
    headers:
      Authorization: "{{auth.cookies.GridAuthorization}}"
    method: POST
    body: { "serverCertificateEncoded": "{{ lookup('file', 'files/mgmt_cert.pem') }}", "caBundleEncoded": "{{ lookup('file', 'files/chain.pem') }}", "privateKeyEncoded": "{{ lookup('file', 'files/mgmt_cert.key') }}" }
    body_format: json
    status_code: 204
    validate_certs: no
  
