---
- name: Load identity variables
  include_vars: sgws_identity.yml

- name: Set or update identity source
  uri:
    url: https://{{ grid_admn }}/api/v2/grid/identity-source
    headers:
      Authorization: "{{ auth.cookies.GridAuthorization }}"
    method: PUT
    body: "{{ identsrc }}"
    body_format: json
    validate_certs: false
