---
- name: Use default certificate for storage API
  uri:
    url: https://{{ grid_admn }}/api/v2/grid/storage-api-certificate/update
    headers:
      Authorization: "{{ auth.cookies.GridAuthorization }}"
    method: POST
    body: {
      "serverCertificateEncoded": null,
      "caBundleEncoded": null,
      "privateKeyEncoded": null
    }
    body_format: json
    status_code: 204
    validate_certs: false
