---
- name: Check if user "{{ acctusr.fullName }}" exists
  uri:
    url: "https://{{ grid_admn }}/api/v2/org/users/\
      {{ acctusr.uniqueName|urlencode }}"
    headers:
      Authorization: "{{ orgauth.cookies.AccountAuthorization }}"
    method: GET
    body_format: json
    validate_certs: false
    status_code: 200, 404
  register: usrchk
  when: orgauth.skipped is not defined

- name: Create new administrator user "{{ acctusr.fullName }}"
  uri:
    url: https://{{ grid_admn }}/api/v2/org/users
    headers:
      Authorization: "{{ orgauth.cookies.AccountAuthorization }}"
    method: POST
    body: "{{ acctusr }}"
    body_format: json
    status_code: 201
    validate_certs: false
  when: orgauth.skipped is not defined and acctgrp.uniqueName is regex("^group/*") and usrchk.status==404 and grpchk.status==404
  register: newusr

- name: Set password for administrator user "{{ acctusr.fullName }}"
  uri:
    url: https://{{ grid_admn }}/api/v2/org/users/{{newusr.json.data.id}}/change-password
    headers:
      Authorization: "{{ orgauth.cookies.AccountAuthorization }}"
    method: POST
    body: "{{ acctusrpass }}"
    body_format: json
    status_code: 204
    validate_certs: false
  when: orgauth.skipped is not defined and acctgrp.uniqueName is regex("^group/*") and usrchk.status==404 and grpchk.status==404
